# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-windows.yaml

on: [push]

env:
  DYLD_LIBRARY_PATH: /opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
  LD_LIBRARY_PATH: /opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
  SENZING_TOOLS_DATABASE_URL: 'sqlite3://na:na@C:\Temp\sqlite\G2C.db'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        go: ["1.21"]
    name: Go ${{ matrix.go }} - windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Download SenzingApi
        run: curl --output senzingapi.zip https://public-read-access.s3.amazonaws.com/staging/SenzingAPI_3.7.0.zip
      - name: Extract SenzingApi
        run: 7z x -y -o"C:\Program Files" senzingapi.zip
      - name: Rename directory
        run: ren "C:\Program Files\senzing" "C:\Program Files\senzing2" && ren "C:\Program Files\senzing2" "C:\Program Files\Senzing"
      - name: Run go test
        run: go test -v -p 1 ./...
