# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-windows.yaml

on: [push]

env:
  DYLD_LIBRARY_PATH: /opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
  LD_LIBRARY_PATH: /opt/senzing/g2/lib:/opt/senzing/g2/lib/macos
  SENZING_TOOLS_DATABASE_URL: 'sqlite3://na:na@nowhere/C:\Temp\sqlite\G2C.db'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        go: ["1.21"]
    name: Go ${{ matrix.go }} - windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install Senzing
        uses: Senzing/github-action-install-senzing@main
      - name: Run go test
        run: go test -v -p 1 ./...
